package Ventanas;

import Utilidades.Modelo;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Duvan Ruiz
 */
public class Reporte extends javax.swing.JFrame {

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        super("Buscar u/o Actualizar");
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        jLabel2.setVisible(false);
        jLabelClientesAtendidos.setVisible(false);
        jTextAreaListado.setVisible(false);
        jLabel3.setVisible(false);
        jLabelRecaudo.setVisible(false);
        jLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelClientesAtendidos = new javax.swing.JLabel();
        jButtonGenerarReporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaListado = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabelRecaudo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelGastoTransporte = new javax.swing.JLabel();
        jButtonCrearPDF = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Stay and Shine", 1, 24)); // NOI18N
        jLabel1.setText("Reportes");

        jLabel2.setText("Numero de clientes atendidos:");

        jButtonGenerarReporte.setBackground(new java.awt.Color(0, 102, 255));
        jButtonGenerarReporte.setText("Generar Reporte");
        jButtonGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarReporteActionPerformed(evt);
            }
        });

        jTextAreaListado.setColumns(20);
        jTextAreaListado.setRows(5);
        jScrollPane1.setViewportView(jTextAreaListado);

        jLabel3.setText("Recaudo:");

        jLabel4.setText("Gastos en transporte:");

        jButtonCrearPDF.setBackground(new java.awt.Color(0, 102, 255));
        jButtonCrearPDF.setText("CrearPDF");
        jButtonCrearPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPDFActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelGastoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelClientesAtendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRecaudo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonGenerarReporte)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonCrearPDF))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerarReporte)
                    .addComponent(jButtonCrearPDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelClientesAtendidos)
                    .addComponent(jLabel3)
                    .addComponent(jLabelRecaudo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelGastoTransporte))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarReporteActionPerformed
        
        
        String lista = Modelo.AGENDA.listarClientes();
        if(lista != ""){
            jLabelClientesAtendidos.setText(Integer.toString(Modelo.AGENDA.numClientes()));
            jTextAreaListado.setText(lista);
            jLabelRecaudo.setText(Float.toString(Modelo.AGENDA.recaudo()));
            jLabelGastoTransporte.setText(Float.toString(Modelo.AGENDA.gastoTransporte()));

            jLabel2.setVisible(true);
            jLabelClientesAtendidos.setVisible(true);
            jTextAreaListado.setVisible(true);
            jLabel3.setVisible(true);
            jLabelRecaudo.setVisible(true);
            jLabel4.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"No hay registros en el sistema.");
        }
    }//GEN-LAST:event_jButtonGenerarReporteActionPerformed

    private void jButtonCrearPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPDFActionPerformed
        Modelo.AGENDA.crearPDF2();
        JOptionPane.showMessageDialog(this, "Se ha creado el archivo PDF");
    }//GEN-LAST:event_jButtonCrearPDFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearPDF;
    private javax.swing.JButton jButtonGenerarReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClientesAtendidos;
    private javax.swing.JLabel jLabelGastoTransporte;
    private javax.swing.JLabel jLabelRecaudo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaListado;
    // End of variables declaration//GEN-END:variables
}
